#!/bin/bash

#
# Test config
#
DISK_TYPE=virtio
declare -A FS

FS[ext2]="mkfs.ext2 -F"
FS[ext3]="mkfs.ext3 -F"
FS[ext4]="mkfs.ext4 -F"
FS[xfs]="mkfs.xfs -f"
FS[jfs]="yes | mkfs.jfs"
FS[reiserfs]="yes | mkfs.reiserfs -f"
FS[btrfs]="mkfs.btrfs"

TEST_COMMAND="sync; date '+%s' > /tmp/TIME_START; for i in `seq -s \" \" 1 3`; do dd bs=1G count=1 if=/dev/zero of=/mnt/disk1/test\$i.img; done; for i in `seq -s \" \" 1 3`; do cp -vf /mnt/disk1/test\$i.img /mnt/disk1/test\$i-2.img; done; rm -vrf /mnt/disk1/test*.img; sync; date '+%s' > /tmp/TIME_END;"
TO_TEST="simple_disk raid0 raid1"
TUNED_STATUS="stop"
TUNED_PROFILES="balanced latency-performance powersave throughput-performance virtual-guest"

#
# Virtual machine config
#

MACHINE_NAME="F18"
MACHINE_IP="192.168.0.120"

#
# Log files config
#

LOG_FILE="/tmp/tuned-results.log"
FAILED_RUN_LOG="/tmp/failedRun"

